-- =====================================================
-- SE CHATBOT DATABASE - Structured Answer System
-- =====================================================
-- Database: se_chatbot_db
-- Contains 50 structured answers (10 per unit) for Software Engineering
-- Answer Format: Definition → Explanation → Example → Conclusion

-- Drop existing database if it exists
DROP DATABASE IF EXISTS se_chatbot_db;

-- Create database
CREATE DATABASE se_chatbot_db;
USE se_chatbot_db;

-- =====================================================
-- TABLE: questions_answers
-- =====================================================
CREATE TABLE questions_answers (
    id INT AUTO_INCREMENT PRIMARY KEY,
    unit_id INT NOT NULL,
    unit_name VARCHAR(255) NOT NULL,
    question_keyword VARCHAR(255) NOT NULL,
    question_title VARCHAR(500) NOT NULL,
    definition LONGTEXT NOT NULL,
    explanation LONGTEXT NOT NULL,
    example LONGTEXT NOT NULL,
    conclusion LONGTEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_unit_id (unit_id),
    INDEX idx_keyword (question_keyword),
    FULLTEXT INDEX ft_question (question_title, question_keyword)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- =====================================================
-- INSERT DATA - 50 Q&A Entries (10 per unit)
-- =====================================================

INSERT INTO questions_answers 
(unit_id, unit_name, question_keyword, question_title, definition, explanation, example, conclusion)
VALUES 
(1, 'Introduction to Software Engineering & Processes', 'software engineering definition', 'What is Software Engineering?', 
'Software engineering is the application of systematic, disciplined, and quantifiable approaches to the development, operation, and maintenance of software systems.', 'Software engineering differs from computer science in that it focuses on the practical aspects of software development including project management, quality assurance, and business considerations. It encompasses methodologies for planning, designing, implementing, testing, and maintaining software systems. The discipline emerged from the need to handle the complexity of large-scale software projects and has become essential in modern software development. Software engineering practices help teams work collaboratively, manage resources effectively, and deliver reliable software products that meet stakeholder requirements.', 'When developing a banking application, software engineers use systematic approaches to gather requirements from banks, design secure systems, implement features with code reviews, test for vulnerabilities, and maintain the system post-deployment. This structured approach ensures the application handles financial transactions reliably.', 'Software engineering provides the framework and practices necessary to develop high-quality software systems efficiently. Understanding its principles is fundamental to creating successful software products in professional environments.');
INSERT INTO questions_answers 
(unit_id, unit_name, question_keyword, question_title, definition, explanation, example, conclusion)
VALUES 
(1, 'Introduction to Software Engineering & Processes', 'software process models', 'What are the main software process models?', 
'Software process models are standardized frameworks that describe the sequence of activities, decisions, and outcomes that lead to the production of a software product.', 'The primary process models include the Waterfall model, which follows a linear sequence of phases; the Iterative model, which refines the software through cycles; and the Incremental model, which delivers software in functional pieces. The Waterfall model works well for projects with well-defined requirements, while iterative approaches are better for projects with changing requirements. Each model has different strengths and is suitable for different project contexts. The choice of model affects team communication, risk management, and the overall development timeline.', 'A government contract project with fixed requirements might use the Waterfall model, proceeding through requirements, design, implementation, testing, and deployment phases sequentially. In contrast, a startup developing a mobile app would use an iterative model, building features incrementally and incorporating user feedback regularly.', 'Selecting the appropriate software process model is crucial for project success. Teams must evaluate project characteristics, stakeholder needs, and organizational constraints to choose the most suitable approach.');
INSERT INTO questions_answers 
(unit_id, unit_name, question_keyword, question_title, definition, explanation, example, conclusion)
VALUES 
(1, 'Introduction to Software Engineering & Processes', 'waterfall model', 'What is the Waterfall Model?', 
'The Waterfall model is a sequential software development process where each phase must be completed before the next phase begins, with limited feedback and iteration.', 'In the Waterfall model, development flows through distinct phases: requirements gathering, design, implementation, testing, and deployment. Each phase produces documentation that serves as input for the next phase. Once a phase is complete, returning to it is difficult and expensive. This model assumes that requirements are well-understood upfront and remain stable throughout development. It emphasizes comprehensive planning and documentation, making it predictable and easy to manage for projects with clear scope.', 'A construction firm developing an enterprise resource planning (ERP) system with fixed requirements would use the Waterfall model. The project manager would gather all requirements from stakeholders upfront, create detailed design documents, implement the entire system, conduct comprehensive testing, and finally deploy it.', 'The Waterfall model is best suited for projects with stable, well-defined requirements and is particularly valuable in regulated industries where extensive documentation and traceability are mandatory.');
INSERT INTO questions_answers 
(unit_id, unit_name, question_keyword, question_title, definition, explanation, example, conclusion)
VALUES 
(1, 'Introduction to Software Engineering & Processes', 'iterative development model', 'What is the Iterative Development Model?', 
'The Iterative development model is a cyclic process where the software is developed in multiple iterations, with each iteration producing a more refined version of the product.', 'In iterative development, requirements are refined through multiple cycles of planning, analysis, design, implementation, and evaluation. Each iteration builds upon the previous one, allowing the team to learn from each cycle and adjust direction accordingly. This model accommodates changing requirements and provides opportunities for stakeholder feedback throughout development. Iterations are typically short (weeks to months), and each produces a working increment of the software. This approach reduces risk by identifying issues early and allows for course correction.', 'A social media platform startup uses iterative development, releasing version 1.0 with basic profile and messaging features. After user feedback, version 2.0 adds photo sharing and notifications, version 3.0 implements video streaming, and so on. Each iteration incorporates user feedback and market learning.', 'Iterative development is ideal for projects with evolving requirements and provides continuous value delivery. It reduces the risk of building the wrong product and fosters continuous improvement.');
INSERT INTO questions_answers 
(unit_id, unit_name, question_keyword, question_title, definition, explanation, example, conclusion)
VALUES 
(1, 'Introduction to Software Engineering & Processes', 'software process activities', 'What are the main activities in any software process?', 
'Core software process activities are the fundamental tasks performed in all software development processes, regardless of the specific methodology employed.', 'All software processes involve four primary activities: software specification (defining what the system should do), design and implementation (deciding how to build it), verification and validation (ensuring it does what was intended), and evolution (maintaining and updating it after release). Software specification involves gathering requirements from stakeholders and documenting system features. Design and implementation translate specifications into actual code. Verification ensures the software meets its specifications, while validation confirms it addresses user needs. Evolution handles bug fixes, performance improvements, and feature additions.', 'When developing an e-commerce website, teams specify requirements like user registration and payment processing; design the architecture and implement the code; verify that login works correctly and validate that users can complete purchases; and evolve the system by adding new payment methods and security features based on user feedback.', 'Understanding these core activities helps teams organize their work effectively and ensures all critical aspects of software development are addressed comprehensively.');
INSERT INTO questions_answers 
(unit_id, unit_name, question_keyword, question_title, definition, explanation, example, conclusion)
VALUES 
(1, 'Introduction to Software Engineering & Processes', 'coping with change software process', 'How do software processes handle changes?', 
'Change management in software processes refers to the systematic approaches used to handle modifications to requirements, design, code, and deployed systems.', 'Software inevitably faces changes from new requirements, discovered bugs, performance issues, and evolving business needs. Effective processes incorporate change management strategies like version control systems that track code changes, configuration management that maintains consistency, change control boards that review and approve changes, and documentation that records why changes were made. Predictive processes like Waterfall anticipate changes upfront through comprehensive planning, while adaptive processes like Agile embrace change through flexible iterations. Modern practices use continuous integration and deployment to manage technical changes efficiently.', 'A healthcare system managing Electronic Health Records discovers a new regulatory requirement. A change request is submitted to the change control board, reviewed for impact, and if approved, integrated into the current iteration. Developers update the system, version control tracks the changes, and the new requirement is tested and deployed.', 'Robust change management ensures that modifications are tracked, evaluated, and implemented systematically, maintaining system integrity and stakeholder satisfaction.');
INSERT INTO questions_answers 
(unit_id, unit_name, question_keyword, question_title, definition, explanation, example, conclusion)
VALUES 
(1, 'Introduction to Software Engineering & Processes', 'rational unified process RUP', 'What is the Rational Unified Process (RUP)?', 
'The Rational Unified Process (RUP) is a comprehensive software development framework that combines iterative development with structured phases and uses the Unified Modeling Language (UML) for design.', 'RUP organizes development into four main phases: Inception (defining the project scope), Elaboration (capturing requirements and designing the architecture), Construction (implementing the system), and Transition (deploying and supporting the system). Within these phases, iterations occur, allowing for refinement and adaptation. RUP emphasizes documentation, quality assurance, and risk management throughout development. It provides detailed workflows, roles, and artifacts that guide teams through complex projects. RUP is particularly valuable for large-scale enterprise projects where structure and documentation are critical.', 'A major telecommunications company developing a new billing system uses RUP. During inception, they define project goals; during elaboration, they capture detailed requirements and design the system architecture; during construction, they build incrementally; and during transition, they deploy to production and provide support.', 'RUP provides a disciplined framework that balances structure with flexibility, making it suitable for organizations that need both systematic development and the ability to adapt to changes.');
INSERT INTO questions_answers 
(unit_id, unit_name, question_keyword, question_title, definition, explanation, example, conclusion)
VALUES 
(1, 'Introduction to Software Engineering & Processes', 'software process improvement', 'What is Software Process Improvement?', 
'Software process improvement refers to systematic efforts to analyze and enhance software development processes, practices, and tools to increase productivity, quality, and efficiency.', 'Process improvement involves assessing current practices, identifying bottlenecks and inefficiencies, implementing enhancements, and measuring the results. Organizations use frameworks like the Capability Maturity Model Integration (CMMI) to evaluate their process maturity and identify areas for improvement. Common improvements include automating repetitive tasks, implementing better code review practices, adopting testing frameworks, improving communication channels, and investing in developer training. Continuous improvement is ongoing, with teams regularly reflecting on what works well and what needs enhancement.', 'A software company notices that bugs frequently slip into production due to inadequate testing. They implement automated unit testing, establish code review protocols, and provide testing training to developers. Over time, they measure improvement through reduced bug rates and faster bug resolution times.', 'Systematic process improvement leads to higher quality software, reduced development time, and better team morale, contributing directly to organizational success.');
INSERT INTO questions_answers 
(unit_id, unit_name, question_keyword, question_title, definition, explanation, example, conclusion)
VALUES 
(1, 'Introduction to Software Engineering & Processes', 'professional software engineering ethics', 'What are the key ethical considerations in professional software engineering?', 
'Professional ethics in software engineering refers to the moral principles and standards that guide engineers in their work and interactions with stakeholders.', 'Software engineers must consider ethics related to privacy, security, transparency, fairness, and social responsibility. Privacy concerns involve protecting user data from unauthorized access. Security ethics require engineers to build robust systems that resist attacks. Transparency means being honest about software capabilities and limitations. Fairness involves ensuring systems don\'t discriminate against groups. Social responsibility means considering the broader impact of software on society. Professional codes of ethics, such as the ACM Code of Ethics and the IEEE Software Engineering Code of Ethics and Professional Practice, provide guidance for engineers facing ethical dilemmas.', 'When developing a hiring algorithm, engineers must ensure it doesn\'t discriminate based on protected characteristics, be transparent about its limitations, secure the applicant data, and consider its societal impact on employment fairness.', 'Adhering to ethical principles builds trust with users and stakeholders, ensures legal compliance, and contributes to creating technology that benefits society.');
INSERT INTO questions_answers 
(unit_id, unit_name, question_keyword, question_title, definition, explanation, example, conclusion)
VALUES 
(1, 'Introduction to Software Engineering & Processes', 'case study lessons learned', 'What are common lessons learned from software project case studies?', 
'Software project case studies analyze real-world projects to extract lessons about what practices lead to success or failure.', 'Case studies of successful projects often show that clear communication, realistic planning, stakeholder engagement, adequate testing, and experienced team leadership are crucial. Failed projects frequently suffered from poor requirements gathering, scope creep, underestimated timelines, inadequate testing, or communication breakdowns. Notable case studies include the Denver Airport baggage system (massive cost overruns), the Ariane 5 rocket failure (insufficient testing), and successful transformations like Netflix\'s shift to cloud computing. These lessons highlight the importance of technical excellence combined with solid project management, realistic planning, and continuous stakeholder involvement.', 'The Denver Airport baggage system case study showed that failing to test integrated components and not addressing scope creep led to a three-year delay and $500 million overrun. In contrast, successful projects like Google\'s infrastructure demonstrate the value of architectural excellence, testing discipline, and continuous improvement.', 'Learning from both successes and failures of other projects helps teams avoid common pitfalls and adopt practices that demonstrate proven effectiveness.');
INSERT INTO questions_answers 
(unit_id, unit_name, question_keyword, question_title, definition, explanation, example, conclusion)
VALUES 
(2, 'Agile Software Development & Requirements Engineering', 'agile methods principles', 'What are the core principles of Agile software development?', 
'Agile software development is an approach that emphasizes iterative development, customer collaboration, and responding to change over following a predetermined plan.', 'The Agile Manifesto outlines four core values: individuals and interactions over processes and tools, working software over comprehensive documentation, customer collaboration over contract negotiation, and responding to change over following a plan. Agile methodologies like Scrum and Extreme Programming implement these values through practices such as short iterations (sprints), daily standups, continuous feedback, and regular releases. Agile teams are self-organizing, cross-functional, and empowered to make decisions. The approach recognizes that requirements evolve throughout development and aims to minimize waste while maximizing delivered value.', 'An Agile team developing a mobile banking app works in two-week sprints. They collaborate closely with the bank\'s product manager, deliver working features every two weeks, gather user feedback, and adjust priorities based on feedback and emerging needs.', 'Agile principles enable teams to respond quickly to changing requirements and deliver value incrementally, leading to higher customer satisfaction and reduced project risk.');
INSERT INTO questions_answers 
(unit_id, unit_name, question_keyword, question_title, definition, explanation, example, conclusion)
VALUES 
(2, 'Agile Software Development & Requirements Engineering', 'scrum methodology', 'What is Scrum and how does it work?', 
'Scrum is an Agile framework for managing software development projects through iterative cycles called sprints, with defined roles, ceremonies, and artifacts.', 'Scrum organizes work into two-week to four-week sprints. The Product Owner maintains a prioritized backlog of requirements. During sprint planning, the team commits to items from the backlog they can complete in the sprint. Daily standups track progress and identify obstacles. The development team works to complete committed items, and the sprint concludes with a review demonstrating completed work and a retrospective for continuous improvement. Scrum defines three key roles: Product Owner (represents stakeholders and prioritizes requirements), Scrum Master (facilitates the process and removes obstacles), and Development Team (delivers the product).', 'A web development team uses Scrum with two-week sprints. The Product Owner prioritizes the backlog with features like \'user authentication\', \'dashboard\', and \'reporting\'. The team commits to completing the first three items in the upcoming sprint, works collaboratively, attends daily standups, reviews completed work with stakeholders, and identifies improvements in the retrospective.', 'Scrum provides a structured yet flexible framework that enables teams to deliver value incrementally while maintaining transparency and continuous improvement.');
INSERT INTO questions_answers 
(unit_id, unit_name, question_keyword, question_title, definition, explanation, example, conclusion)
VALUES 
(2, 'Agile Software Development & Requirements Engineering', 'extreme programming XP', 'What is Extreme Programming (XP)?', 
'Extreme Programming (XP) is an Agile software development methodology that emphasizes technical excellence and customer satisfaction through practices like pair programming, continuous integration, and test-driven development.', 'XP takes good software development practices to extreme levels. Key practices include pair programming (two developers working at one computer), test-driven development (writing tests before code), continuous integration (frequently merging code), simple design (avoiding unnecessary complexity), and frequent releases. XP teams maintain high code quality, reduce defects, and enable rapid change. The methodology is particularly effective for projects with evolving requirements and high change rates. XP practices create a sustainable pace of work and high team morale through shared responsibility and collective code ownership.', 'An XP team developing a financial trading platform practices test-driven development, writing tests for each feature before implementation. Developers work in pairs, code is integrated continuously (multiple times daily), and simple elegant designs are maintained. This results in extremely high code quality and the ability to adapt quickly to market changes.', 'XP\'s emphasis on technical practices and customer collaboration creates high-quality, adaptable software that maintains a sustainable development pace.');
INSERT INTO questions_answers 
(unit_id, unit_name, question_keyword, question_title, definition, explanation, example, conclusion)
VALUES 
(2, 'Agile Software Development & Requirements Engineering', 'plan-driven development', 'What is Plan-Driven Development?', 
'Plan-driven development is a software process approach that emphasizes detailed planning upfront, comprehensive documentation, and following the plan with controlled changes.', 'Plan-driven approaches like the Waterfall model and RUP create detailed plans before development begins, including complete specifications, design documents, and timelines. Changes are managed through formal change control processes. Plan-driven development works well when requirements are well-understood and stable, such as in regulated industries or fixed-price contracts. It provides predictability, clear documentation for maintenance, and easy handoff between teams. However, it requires accurate upfront requirements elicitation and assumes the environment remains relatively stable.', 'A government defense contractor developing weapons control software uses plan-driven development. They spend months gathering requirements, creating detailed specifications, planning the entire project, and documenting everything comprehensively before coding begins. Changes must go through formal approval processes.', 'Plan-driven development provides predictability and comprehensive documentation, making it valuable for projects with stable requirements and regulatory compliance needs.');
INSERT INTO questions_answers 
(unit_id, unit_name, question_keyword, question_title, definition, explanation, example, conclusion)
VALUES 
(2, 'Agile Software Development & Requirements Engineering', 'scaling agile methods', 'How are Agile methods scaled for large projects?', 
'Scaling Agile refers to applying Agile principles and practices to large, complex projects involving multiple teams and extensive organizational coordination.', 'Scaling Agile frameworks like SAFe (Scaled Agile Framework), LeSS (Large-Scale Scrum), and Spotify Model extend Agile practices to handle organizational complexity. Scaling challenges include coordinating multiple teams, maintaining alignment on goals, managing dependencies between teams, and ensuring organizational processes don\'t impede Agility. Scaled Agile typically uses hierarchical planning with program-level coordination, cross-team dependencies management, and synchronized release schedules. Successful scaling maintains Agile values while adding necessary coordination structure. Key practices include program increment planning, architectural governance, and dependency management.', 'A large financial services company uses SAFe to coordinate 30 Scrum teams developing an integrated banking platform. Teams work in synchronized two-week sprints within quarterly program increments. Program-level planning ensures teams align on shared goals while maintaining team-level autonomy.', 'Properly scaled Agile methodologies enable large organizations to maintain Agility and deliver value incrementally while managing complexity and dependencies.');
INSERT INTO questions_answers 
(unit_id, unit_name, question_keyword, question_title, definition, explanation, example, conclusion)
VALUES 
(2, 'Agile Software Development & Requirements Engineering', 'requirements engineering definition', 'What is Requirements Engineering?', 
'Requirements engineering is the systematic process of defining, documenting, and managing software system requirements throughout the development lifecycle.', 'Requirements engineering involves discovering what users and stakeholders need the system to do (functional requirements) and system quality attributes (non-functional requirements). The process includes elicitation (gathering requirements), analysis (understanding and refining them), documentation (recording them clearly), validation (ensuring they\'re correct and complete), and management (tracking changes). Good requirements are clear, unambiguous, testable, and traceable. Poor requirements lead to misaligned software, missed deadlines, and unsatisfied users. Requirements engineering occurs in all processes but is particularly critical in plan-driven approaches where requirements are fixed upfront.', 'When developing an airline reservation system, requirements engineers elicit requirements like \'users must be able to search flights by date and destination\' and non-functional requirements like \'system must handle 10,000 concurrent users\'. They document these, validate with stakeholders, and track them throughout development.', 'Rigorous requirements engineering ensures that development efforts align with user needs and stakeholder expectations, reducing rework and project failures.');
INSERT INTO questions_answers 
(unit_id, unit_name, question_keyword, question_title, definition, explanation, example, conclusion)
VALUES 
(2, 'Agile Software Development & Requirements Engineering', 'functional non-functional requirements', 'What are functional and non-functional requirements?', 
'Functional requirements describe what a system should do, while non-functional requirements describe how the system should perform and its quality attributes.', 'Functional requirements specify system features and capabilities, such as \'the system shall allow users to create accounts\' or \'the system shall generate reports in PDF format\'. Non-functional requirements address performance, security, usability, maintainability, and reliability, such as \'the system shall respond to requests within 2 seconds\', \'the system shall encrypt sensitive data\', or \'the system shall support 99.9% uptime\'. Both types are essential for complete system specifications. Functional requirements define the system\'s behavior, while non-functional requirements define its quality. Neglecting non-functional requirements often leads to systems that work but perform poorly or are difficult to maintain.', 'For an e-commerce website, functional requirements include \'users can add items to a shopping cart\' and \'the system shall process payments securely\'. Non-functional requirements include \'page load time shall be under 2 seconds\', \'the system shall support 100,000 concurrent users\', and \'checkout process shall be completable in under 3 minutes\'.', 'Clear distinction between functional and non-functional requirements ensures comprehensive system specifications that address both behavior and quality concerns.');
INSERT INTO questions_answers 
(unit_id, unit_name, question_keyword, question_title, definition, explanation, example, conclusion)
VALUES 
(2, 'Agile Software Development & Requirements Engineering', 'requirements elicitation techniques', 'What are the main techniques for requirements elicitation?', 
'Requirements elicitation techniques are methods used to discover and gather requirements from stakeholders and users.', 'Common elicitation techniques include interviews (direct conversations with stakeholders), questionnaires (written questions to gather input from many people), observation (watching users work to understand their processes), prototyping (building mockups to explore requirements), and focus groups (group discussions with key stakeholders). Workshops bring stakeholders together for intensive requirement gathering sessions. Document analysis examines existing systems or similar projects. Different techniques work for different situations: interviews are great for deep understanding, questionnaires reach many people efficiently, and prototyping helps clarify fuzzy requirements. Effective elicitation often combines multiple techniques.', 'When developing an enterprise resource planning system, requirements engineers conduct interviews with department heads, observe current workflows, review existing processes, hold workshops with representatives from finance, HR, and operations, and create prototypes to explore interface designs.', 'Using appropriate elicitation techniques ensures comprehensive and accurate requirements capture from diverse stakeholders.');
INSERT INTO questions_answers 
(unit_id, unit_name, question_keyword, question_title, definition, explanation, example, conclusion)
VALUES 
(2, 'Agile Software Development & Requirements Engineering', 'requirements specification document', 'What should be included in a Software Requirements Specification (SRS)?', 
'A Software Requirements Specification (SRS) is a comprehensive document that details all functional and non-functional requirements for a software system.', 'A complete SRS includes: system overview and scope, functional requirements (what the system does), non-functional requirements (performance, security, usability standards), system constraints, user stories or use cases, interface requirements, data requirements, and acceptance criteria. The SRS serves as a contract between developers and stakeholders, ensuring mutual understanding. It should be organized logically, use clear and unambiguous language, include diagrams and examples, and be testable (each requirement should be verifiable). A well-written SRS reduces misunderstandings, facilitates design, and serves as a reference for maintenance.', 'An SRS for a patient management system includes functional requirements like \'doctors can view patient medical history\', non-functional requirements like \'system shall be HIPAA compliant\', interface requirements describing the layout, constraints like \'must integrate with existing hospital systems\', and acceptance criteria for each requirement.', 'A well-structured SRS serves as the foundation for successful software development by aligning stakeholder expectations and guiding the development team.');
INSERT INTO questions_answers 
(unit_id, unit_name, question_keyword, question_title, definition, explanation, example, conclusion)
VALUES 
(2, 'Agile Software Development & Requirements Engineering', 'requirements validation management', 'What are requirements validation and management?', 
'Requirements validation ensures that requirements correctly represent what stakeholders need, while requirements management tracks and controls requirement changes throughout the project lifecycle.', 'Validation techniques include reviews (expert evaluation of requirements), prototyping (building models to verify requirements), testing against use cases (ensuring requirements address real user scenarios), and traceability analysis (ensuring all requirements are covered in design and testing). Requirements management involves tracking requirements, managing changes through formal processes, maintaining version control, and ensuring traceability. Traceability matrices link requirements to design components, code, and tests, enabling impact analysis when changes are proposed. Effective validation prevents building the wrong system, while effective management controls scope creep and maintains project coherence.', 'For a mobile banking app, requirements are validated through stakeholder reviews, prototyping the interface, and testing against real user scenarios. Changes are tracked using a requirements management tool, impact analysis determines effects on other requirements, and traceability ensures each requirement is addressed in design and testing.', 'Rigorous validation and management of requirements ensure that the final product aligns with stakeholder needs and maintains project focus throughout development.');
INSERT INTO questions_answers 
(unit_id, unit_name, question_keyword, question_title, definition, explanation, example, conclusion)
VALUES 
(3, 'System Modeling & Architectural Design', 'context model system', 'What is a context model in system modeling?', 
'A context model is a diagram that shows a system and its relationship with the external environment, including users, other systems, and external entities.', 'The context model defines system boundaries by identifying what is inside the system and what is external. It shows external entities that interact with the system, data flows between the system and external entities, and the system as a single process or component. Context models are typically represented as Data Flow Diagrams (DFDs) showing the system as a single bubble at the center with external entities around it. The model helps stakeholders understand what the system will and won\'t do, facilitates discussion of requirements, and serves as a starting point for detailed analysis. Creating a context model requires understanding the operational environment and identifying all external systems or users that interact with the system.', 'For an automated teller machine (ATM), the context model shows the ATM at the center, with external entities like the customer, the bank\'s central computer system, and the card network (Visa/Mastercard). Data flows show the customer inserting a card, requesting money, the ATM communicating with the bank, and money being dispensed.', 'Context models provide a clear visualization of system scope and boundaries, facilitating shared understanding among stakeholders about system responsibilities.');
INSERT INTO questions_answers 
(unit_id, unit_name, question_keyword, question_title, definition, explanation, example, conclusion)
VALUES 
(3, 'System Modeling & Architectural Design', 'interaction model UML', 'What is an interaction model and how is it represented in UML?', 
'An interaction model describes how users or external systems interact with a software system, typically shown through use case diagrams or sequence diagrams.', 'Interaction models capture the dynamic behavior and communication patterns in a system. Use case diagrams show actors (users or external systems), use cases (system functions), and relationships between them. Use cases describe sequences of interactions between actors and the system to achieve a goal. Sequence diagrams show the time-ordered messages exchanged between objects during a specific scenario. Collaboration diagrams (also called communication diagrams) show interactions between objects with emphasis on relationships. State machines show how objects change state in response to events. These diagrams help developers understand system behavior, identify missing requirements, and communicate requirements to stakeholders.', 'For an online shopping system, a use case diagram shows actors like customer and payment processor with use cases like \'browse products\', \'add to cart\', and \'checkout\'. A sequence diagram for the \'checkout\' use case shows the time-ordered messages: customer enters payment info, system validates card, payment processor charges card, system confirms order, and confirmation email is sent.', 'Interaction models provide clear visualizations of how the system behaves in response to user actions and system events, ensuring clear communication of requirements.');
INSERT INTO questions_answers 
(unit_id, unit_name, question_keyword, question_title, definition, explanation, example, conclusion)
VALUES 
(3, 'System Modeling & Architectural Design', 'structural model UML class diagram', 'What is a structural model and how are class diagrams used?', 
'A structural model describes the organization and relationships between system components, typically shown using UML class diagrams for object-oriented systems.', 'Structural models show the static structure of a system, including classes, their attributes, methods, and relationships. Class diagrams represent classes as boxes with attributes (data) and operations (methods), showing visibility (public, private, protected). Relationships between classes include inheritance (generalization/specialization), association (relationships between classes), aggregation (whole-part relationships), and composition (strong whole-part relationships). Class diagrams provide a blueprint for developers to implement the system and help identify missing or incorrectly modeled abstractions. They serve as documentation of the system\'s architecture and facilitate code generation in some development tools.', 'For a university system, class diagrams show classes like Student, Course, and Instructor. Student has attributes like studentID and enrolledCourses. The diagram shows that Student is related to Course through an enrollment association and that Instructor teaches Course. These relationships guide implementation.', 'Structural models provide the blueprint for system design, ensuring that developers understand class relationships and enabling systematic implementation.');
INSERT INTO questions_answers 
(unit_id, unit_name, question_keyword, question_title, definition, explanation, example, conclusion)
VALUES 
(3, 'System Modeling & Architectural Design', 'behavioral model state machine', 'What is a behavioral model and how are state machines used?', 
'A behavioral model describes how a system behaves over time, including state changes and event responses, typically represented through state machine diagrams.', 'State machine diagrams show the states an object or system can be in and the transitions between states triggered by events or conditions. Each state represents a distinct condition, and transitions show how the system moves from one state to another. States can have actions (activities performed while in the state) and entry/exit actions. Guards (conditions) determine whether a transition should occur. State machines are particularly useful for modeling systems with complex control flow, like workflow systems, user interfaces, and communication protocols. They help identify missing behaviors, prevent invalid state transitions, and facilitate testing by showing all possible behavior paths.', 'A workflow system modeling a document approval process might have states like \'Draft\', \'Submitted\', \'Under Review\', \'Approved\', and \'Published\'. Transitions occur when events like \'submit\', \'approve\', or \'reject\' are triggered, with guards ensuring only authorized users can approve documents.', 'State machine diagrams clearly capture system behavior and state transitions, enabling developers to implement complex control flow correctly.');
INSERT INTO questions_answers 
(unit_id, unit_name, question_keyword, question_title, definition, explanation, example, conclusion)
VALUES 
(3, 'System Modeling & Architectural Design', 'model-driven engineering', 'What is Model-Driven Engineering (MDE)?', 
'Model-Driven Engineering is a software development approach that emphasizes the creation and transformation of models as the primary development artifacts.', 'In MDE, developers create abstract models at a high level of abstraction, and these models drive the development process. Models can be transformed into other models (model-to-model transformation) or directly into code (model-to-code generation). The approach reduces manual coding, improves consistency, and enables automatic generation of documentation. Key concepts include Domain-Specific Languages (DSLs) tailored to specific problem domains, metamodels that define the structure of models, and transformation rules. MDE particularly benefits projects that require consistency across many similar components or where domain-specific knowledge can be captured in models.', 'In Enterprise Architecture, MDE tools allow architects to model business processes, systems, and data at a high level. These models can be transformed into implementation code, documentation, and deployment configurations automatically, reducing manual work and improving consistency.', 'Model-Driven Engineering increases development efficiency and consistency by using models as the primary development artifacts and automating transformation to code.');
INSERT INTO questions_answers 
(unit_id, unit_name, question_keyword, question_title, definition, explanation, example, conclusion)
VALUES 
(3, 'System Modeling & Architectural Design', 'architectural design decisions', 'What are architectural design decisions?', 
'Architectural design decisions are choices about the overall structure of a system that have significant impact on its properties like performance, security, and maintainability.', 'Architectural decisions determine major system components, their relationships, data flow, communication patterns, and technology choices. Key decisions include whether to use monolithic or microservices architecture, client-server or peer-to-peer patterns, database technology selection, security architecture, and deployment strategy. These decisions are typically made early in development and are difficult and expensive to change later, so they require careful consideration. Decisions should balance multiple concerns like performance, security, scalability, maintainability, and cost. Documenting decisions and their rationale (Architecture Decision Records) helps future developers understand why certain choices were made.', 'A startup building a scaling social media platform must decide between a monolithic architecture (simpler initially) or microservices (better for scaling). They choose microservices, deciding that independent team development and granular scaling outweigh the added operational complexity. This decision drives subsequent component design choices.', 'Well-made architectural decisions establish a foundation for system success, while poor decisions can necessitate costly rewrites later in the project.');
INSERT INTO questions_answers 
(unit_id, unit_name, question_keyword, question_title, definition, explanation, example, conclusion)
VALUES 
(3, 'System Modeling & Architectural Design', 'architectural views patterns', 'What are architectural views and patterns?', 
'Architectural views are different perspectives of a system\'s architecture, while architectural patterns are proven, reusable solutions to common architectural problems.', 'The \'4+1 view model\' describes architecture through five perspectives: logical view (system structure), process view (runtime behavior), physical view (deployment), development view (components and modules), and scenarios (how views relate). Different stakeholders need different views: managers focus on physical view, developers on logical and development views, system engineers on process view. Architectural patterns like Model-View-Controller (MVC) separate concerns, client-server patterns distribute processing, and message-oriented patterns enable loose coupling. Patterns provide proven solutions that reduce design risk and improve communication through shared vocabulary.', 'An enterprise system architecture uses the 4+1 view model: the logical view shows business domains, the process view shows application servers and databases, the physical view shows deployment across data centers, the development view shows code organization, and scenarios show how a user request flows through the system.', 'Multiple architectural views provide comprehensive understanding for different stakeholders, while patterns offer proven solutions that accelerate design and reduce risk.');
INSERT INTO questions_answers 
(unit_id, unit_name, question_keyword, question_title, definition, explanation, example, conclusion)
VALUES 
(3, 'System Modeling & Architectural Design', 'application architectures', 'What are common application architectures?', 
'Application architectures are standard patterns that are adapted for specific applications, representing proven solutions for organizing software systems.', 'Common application architectures include transaction-based applications (process user requests and maintain databases), interactive systems (heavy user interaction with real-time response), embedded systems (software controlling physical devices), batch systems (processing large data sets), event-driven systems (react to external events), and service-oriented architectures (composed of loosely coupled services). Each architecture type has characteristic components, data flows, and control mechanisms. Selecting the appropriate architecture for the application type is crucial, as mismatches lead to performance problems and difficult maintenance. Modern applications often combine multiple architecture patterns.', 'An airline reservation system is a transaction-based architecture handling user requests to book flights, update reservations, and process payments. A video streaming service uses event-driven architecture where user actions (play, pause, seek) trigger streaming events. Both are optimized for their specific use cases.', 'Matching application architecture to the system\'s characteristics ensures efficient implementation and appropriate system behavior.');
INSERT INTO questions_answers 
(unit_id, unit_name, question_keyword, question_title, definition, explanation, example, conclusion)
VALUES 
(3, 'System Modeling & Architectural Design', 'microservices architecture', 'What is microservices architecture?', 
'Microservices architecture is an approach to building systems as a collection of small, independent services that communicate over networks, each handling a specific business capability.', 'In microservices, a large application is decomposed into services handling distinct business functions. Each service is independently deployable, scalable, and maintainable, often written in different languages if appropriate. Services communicate through APIs (REST, gRPC, message queues). Microservices enable independent team development, flexible technology choices, and granular scaling. However, they introduce complexity in managing distributed systems, data consistency across services, and network communication latency. Successful microservices require strong DevOps practices, service mesh technologies for management, and careful service boundary definition.', 'Netflix uses microservices for different functions: a service for user authentication, a service for content discovery, a service for streaming, a service for recommendations. Each service is independently developed, deployed, and scaled based on demand.', 'Microservices enable organizational agility and system scalability but require mature engineering practices and operational infrastructure.');
INSERT INTO questions_answers 
(unit_id, unit_name, question_keyword, question_title, definition, explanation, example, conclusion)
VALUES 
(3, 'System Modeling & Architectural Design', 'architecture documentation', 'How should software architecture be documented?', 
'Architecture documentation describes the overall structure, design decisions, and key patterns of a software system in formats that stakeholders can understand.', 'Effective architecture documentation includes multiple components: architecture overview (high-level system structure), component diagrams (major system components and relationships), architectural views (different perspectives like logical, process, physical), design decisions with rationale, patterns used and their justification, constraints and assumptions, and guidelines for implementation. Documentation should use consistent notation (like UML), be accessible to different audiences (from technical developers to non-technical managers), and include examples and scenarios. Living documentation that evolves with the system is more valuable than static documents that quickly become outdated. Tools like C4 model provide structured approaches to architecture visualization.', 'An e-commerce platform documents its architecture with a C4 diagram showing systems context, containers (web app, mobile app, API server, database), components (authentication module, product catalog, order processing), and code organization, supplemented with documented architectural decisions and deployment procedures.', 'Clear architecture documentation facilitates communication, guides implementation, and enables stakeholders to make informed decisions about the system.');
INSERT INTO questions_answers 
(unit_id, unit_name, question_keyword, question_title, definition, explanation, example, conclusion)
VALUES 
(4, 'Design and Implementation', 'object-oriented design principles', 'What are the principles of object-oriented design?', 
'Object-oriented design principles are guidelines for creating well-structured, maintainable object-oriented software systems.', 'Key principles include abstraction (exposing essential features while hiding complexity), encapsulation (bundling data and methods while controlling access), inheritance (creating class hierarchies to share common properties), and polymorphism (objects responding differently to the same message). Additional principles include the Single Responsibility Principle (each class should have one reason to change), Open/Closed Principle (open for extension, closed for modification), Liskov Substitution Principle (derived classes should be usable wherever base classes are expected), and Dependency Inversion Principle (depend on abstractions, not concrete implementations). SOLID principles (an acronym for five OO design principles) provide a framework for creating maintainable and extensible designs.', 'A good design represents a Shape hierarchy with an abstract Shape class and concrete subclasses like Circle and Rectangle. The abstract Shape defines the draw() method (abstraction and polymorphism), each subclass implements draw() differently (polymorphism), and each class has well-defined responsibilities (single responsibility).', 'Following object-oriented design principles creates systems that are easier to understand, modify, extend, and maintain.');
INSERT INTO questions_answers 
(unit_id, unit_name, question_keyword, question_title, definition, explanation, example, conclusion)
VALUES 
(4, 'Design and Implementation', 'UML class diagram design', 'How is UML used in detailed design?', 
'UML (Unified Modeling Language) is used in detailed design to precisely specify class structures, relationships, and responsibilities before implementation.', 'During detailed design, developers create comprehensive class diagrams showing all classes, attributes with types, methods with signatures and visibility, and detailed relationships. Design patterns are often represented through UML diagrams. Sequence diagrams show exact message flows for important scenarios. Activity diagrams show complex control flows. Package diagrams show code organization. This detailed modeling catches design issues before coding, facilitates code generation tools, and provides clear documentation for implementation. UML bridges the gap between architectural design and code implementation.', 'For an e-commerce order system, a detailed class diagram shows the Order class with attributes (orderID: int, orderDate: DateTime) and methods (addItem(), removeItem(), calculateTotal()), Item class with similar structure, and relationships between them including cardinality (one order contains many items).', 'Detailed UML modeling ensures that designs are clear, complete, and ready for implementation.');
INSERT INTO questions_answers 
(unit_id, unit_name, question_keyword, question_title, definition, explanation, example, conclusion)
VALUES 
(4, 'Design and Implementation', 'design patterns Gang of Four', 'What are design patterns and why are they important?', 
'Design patterns are reusable solutions to common problems in software design, providing templates for solving similar design challenges.', 'Design patterns, catalogued by the \'Gang of Four\' in their seminal work, are divided into creational patterns (object creation mechanisms like Singleton and Factory), structural patterns (object composition like Adapter and Decorator), and behavioral patterns (object interaction and responsibility like Observer and Strategy). Patterns promote code reuse, provide proven solutions that are less error-prone than novel designs, improve communication through shared vocabulary, and make code more maintainable and extensible. However, patterns shouldn\'t be overused; applying them only when they solve a genuine problem results in simpler, more maintainable code.', 'The Singleton pattern ensures only one instance of a class exists (useful for database connections or configuration managers). The Factory pattern centralizes object creation (useful for creating different implementations based on context). The Observer pattern lets objects notify interested parties of state changes (useful for event handling in UI frameworks).', 'Understanding and appropriately applying design patterns leads to more maintainable, extensible, and professionally designed software systems.');
INSERT INTO questions_answers 
(unit_id, unit_name, question_keyword, question_title, definition, explanation, example, conclusion)
VALUES 
(4, 'Design and Implementation', 'implementation issues open source', 'What are common implementation issues and how is open source software developed?', 
'Implementation issues are challenges that arise during the coding phase, while open source development represents a collaborative approach to software creation.', 'Implementation issues include code organization and structure, reusing existing code versus writing new code, error handling strategies, and managing platform-specific code. Good practices include using version control systems, code review processes, and automated testing. Open source software is developed collaboratively by volunteer or sponsored contributors who publicly share source code. Key aspects include transparent development (anyone can view the code), distributed teams (contributors worldwide), licensing (defining how code can be used), community management (coordinating contributors), and release management. Open source leverages community intelligence to catch bugs and improve quality.', 'Linux is developed by thousands of volunteers globally. Contributors propose changes through patches, code is reviewed by maintainers, merged into version control, and released periodically. The transparent development process and large contributor base drive rapid innovation and quality improvements.', 'Understanding implementation issues and open source principles leads to better code quality and, for open source projects, stronger community participation.');
INSERT INTO questions_answers 
(unit_id, unit_name, question_keyword, question_title, definition, explanation, example, conclusion)
VALUES 
(4, 'Design and Implementation', 'reusable components frameworks', 'What are reusable components and frameworks?', 
'Reusable components are software modules designed to be used in multiple projects, while frameworks provide the foundational structure for building applications.', 'Components can range from simple libraries providing specific functionality (like a JSON parser) to complex frameworks providing architecture, services, and extension points. Frameworks like Spring for Java or Django for Python provide structure, common services (database access, security, logging), and extension mechanisms. Using existing components and frameworks accelerates development, reduces costs, leverages tested and proven solutions, and provides consistency across projects. However, frameworks impose architectural constraints, require learning, and create dependencies. Choosing appropriate components and frameworks is an important design decision.', 'React is a framework for building user interfaces, providing component-based architecture, state management, and rendering optimization. Developers build applications by creating components that compose together, leveraging React\'s framework services rather than building everything from scratch.', 'Strategic use of components and frameworks accelerates development and improves quality, though care must be taken to avoid over-complicating solutions.');
INSERT INTO questions_answers 
(unit_id, unit_name, question_keyword, question_title, definition, explanation, example, conclusion)
VALUES 
(4, 'Design and Implementation', 'coding standards guidelines', 'Why are coding standards and guidelines important?', 
'Coding standards are agreed-upon conventions for writing code that improve readability, maintainability, and consistency across a project or organization.', 'Standards cover naming conventions (how to name variables, methods, classes), code formatting (indentation, line length, spacing), documentation (comments, docstrings), structure (organizing code files and packages), and error handling. Standards improve code readability so developers can understand code written by others, facilitate code reviews, reduce bugs through consistent approaches, and make code maintenance easier. Many languages have community-established standards (PEP 8 for Python, Google Java Style Guide). Tools like linters can automatically enforce standards. While standards initially feel constraining, they pay dividends in team productivity and code quality.', 'A project adopts PEP 8 for Python, requiring lowercase with underscores for variable names, docstrings for all functions, and specific indentation. While developers initially find this restrictive, the resulting consistency makes code reviews easier and the codebase more maintainable.', 'Established coding standards improve code quality, facilitate team collaboration, and reduce maintenance costs significantly.');
INSERT INTO questions_answers 
(unit_id, unit_name, question_keyword, question_title, definition, explanation, example, conclusion)
VALUES 
(4, 'Design and Implementation', 'refactoring code quality', 'What is refactoring and why is it important?', 
'Refactoring is the process of improving code quality without changing its external behavior, making code more readable and maintainable.', 'Refactoring techniques include extracting methods (breaking large methods into smaller ones), renaming variables and methods for clarity, removing duplicated code, simplifying conditional logic, and reorganizing classes. Refactoring should be done incrementally with automated tests ensuring functionality remains unchanged. Regular refactoring prevents code from deteriorating into \'technical debt\' that becomes increasingly difficult to maintain. Refactoring is particularly important when inheriting legacy code. Modern IDEs provide refactoring tools that mechanically apply transformations safely.', 'A method containing complex nested conditionals can be refactored by extracting the conditions into named helper methods, making the logic clearer and the code more maintainable. Another example is consolidating similar code blocks into a shared method to eliminate duplication.', 'Regular refactoring maintains code quality and prevents accumulated technical debt that slows development over time.');
INSERT INTO questions_answers 
(unit_id, unit_name, question_keyword, question_title, definition, explanation, example, conclusion)
VALUES 
(4, 'Design and Implementation', 'version control systems', 'What is version control and why is it essential?', 
'Version control systems track changes to code over time, enabling collaboration, change history, and recovery from mistakes.', 'Version control systems like Git allow multiple developers to work on the same codebase concurrently, track who made changes and why through commit messages, revert to previous versions if needed, create branches for parallel development, and merge changes carefully. Distributed version control systems like Git enable offline work and are more resilient than centralized systems. Modern development practices require version control; it\'s not optional. Features like branching enable feature development without affecting the main codebase, tags mark important versions, and hooks can automate testing or deployment.', 'A team uses Git with a workflow where developers create feature branches, commit changes with descriptive messages, push to a repository, create pull requests for review, and merge after approval. The main branch always contains working code, and the full history is available for debugging.', 'Version control is fundamental to professional software development, enabling safe collaboration, change tracking, and easy recovery from mistakes.');
INSERT INTO questions_answers 
(unit_id, unit_name, question_keyword, question_title, definition, explanation, example, conclusion)
VALUES 
(4, 'Design and Implementation', 'code reviews peer review', 'What are the benefits of code reviews?', 
'Code reviews are a quality practice where developers review each other\'s code before it\'s integrated into the main codebase.', 'Code reviews catch bugs and design issues early, share knowledge across the team, ensure code meets standards, and help less experienced developers learn from more experienced ones. Review processes typically involve creating a change request (pull request), having one or more reviewers examine the code, discussing improvements, making revisions, and merging after approval. Effective reviews require a constructive culture where feedback is seen as valuable, not personal criticism. Tools like GitHub facilitate code reviews with commenting and approval workflows. Studies show that code reviews significantly reduce defects and improve code quality.', 'A developer implements a feature, creates a pull request, and requests review from team members. Reviewers examine the code, ask clarifying questions, suggest improvements, and the developer responds to feedback. After reaching consensus, the code is merged.', 'Code reviews are a proven practice that improves code quality, catches issues early, and builds team knowledge and cohesion.');
INSERT INTO questions_answers 
(unit_id, unit_name, question_keyword, question_title, definition, explanation, example, conclusion)
VALUES 
(4, 'Design and Implementation', 'documentation maintenance', 'How should code documentation be maintained?', 
'Code documentation explains how code works and how to use it, maintained as part of the development process to remain accurate and useful.', 'Documentation includes API documentation (how to use classes and methods), inline comments (explaining complex logic), README files (how to build and run the system), architecture documentation (how components relate), and usage examples. Documentation should be kept close to code (in docstrings or nearby files) so developers see it easily. Automated documentation tools (like Javadoc or Sphinx) generate documentation from structured comments. Documentation should be updated when code changes; outdated documentation is worse than no documentation as it misleads developers. Living documentation that evolves with code is more valuable than static documentation.', 'A function includes a docstring explaining what it does, parameters it accepts, and values it returns. When the function is modified, the docstring is updated. Automated documentation tools generate HTML documentation from these docstrings.', 'Well-maintained documentation makes code more usable and maintainable, reducing the learning curve for new team members and enabling effective collaboration.');
INSERT INTO questions_answers 
(unit_id, unit_name, question_keyword, question_title, definition, explanation, example, conclusion)
VALUES 
(5, 'Software Testing & Dependability', 'software testing definition', 'What is software testing?', 
'Software testing is a quality assurance practice that systematically exercises software to discover and document defects and verify that it meets specified requirements.', 'Testing differs from debugging: testing finds problems, debugging fixes them. Comprehensive testing is impossible (infinite input combinations), so testing focuses on strategic areas to maximize defect detection. Testing includes multiple levels: unit testing (testing individual components), integration testing (testing component interactions), system testing (testing complete system), and acceptance testing (verifying requirements are met). Testing activities occur throughout development, not just at the end. Effective testing requires planning (what to test and how), test case design (choosing test scenarios), test execution (running tests and recording results), and defect reporting (documenting found issues).', 'A web application goes through unit testing (testing individual functions), integration testing (testing login with database connection), system testing (testing complete workflow), and acceptance testing (ensuring the system meets business requirements).', 'Systematic testing throughout development is essential for delivering reliable software that meets user expectations and regulatory requirements.');
INSERT INTO questions_answers 
(unit_id, unit_name, question_keyword, question_title, definition, explanation, example, conclusion)
VALUES 
(5, 'Software Testing & Dependability', 'development testing unit testing', 'What is development testing and unit testing?', 
'Development testing is performed by developers during the coding phase, with unit testing being the practice of testing individual program components in isolation.', 'Unit testing involves writing tests for individual functions or methods, exercising different inputs and conditions to verify correct behavior. Unit tests are automated, run frequently (after every code change), and serve as regression tests (detecting if changes break existing functionality). Test-driven development (TDD) involves writing unit tests before implementing features, using tests to drive design. Unit tests should be independent (not relying on other tests), fast (enabling frequent execution), and comprehensive (covering normal cases, boundary conditions, and error cases). Frameworks like JUnit (Java), pytest (Python), and Jasmine (JavaScript) facilitate unit testing.', 'A function that calculates monthly interest has unit tests verifying correct calculation for typical amounts, boundary cases (minimum and maximum rates), and error cases (negative amounts). When the interest calculation logic is modified, all tests are re-run to ensure the change doesn\'t break existing functionality.', 'Unit testing during development catches defects early when they\'re cheap to fix, and provides regression tests that maintain code quality as systems evolve.');
INSERT INTO questions_answers 
(unit_id, unit_name, question_keyword, question_title, definition, explanation, example, conclusion)
VALUES 
(5, 'Software Testing & Dependability', 'test-driven development TDD', 'What is Test-Driven Development (TDD)?', 
'Test-Driven Development is an approach where unit tests are written before implementing features, with the tests driving the design and ensuring requirements are met.', 'In TDD, developers follow a red-green-refactor cycle: first write a failing test (red), then implement minimal code to pass the test (green), then improve the code quality (refactor). This approach ensures all code is tested, prevents over-engineering, and documents requirements through tests. TDD requires discipline and upfront thought but results in higher code quality, better design (tests drive simpler, more testable designs), and faster debugging (if a test fails, the most recent change is likely the cause). TDD is particularly valuable in Agile environments where continuous code changes occur.', 'When implementing a shopping cart\'s \'remove item\' function, a developer first writes a test expecting removal to succeed when the item exists. The test fails (red). Then the developer implements the minimum code to pass the test. Finally, the code is refactored if needed. This ensures the function works correctly and is testable.', 'Test-driven development produces higher quality code with comprehensive test coverage and better design, despite initially appearing slower.');
INSERT INTO questions_answers 
(unit_id, unit_name, question_keyword, question_title, definition, explanation, example, conclusion)
VALUES 
(5, 'Software Testing & Dependability', 'release testing system testing', 'What is release testing and system testing?', 
'Release testing verifies that the complete system meets requirements and is ready for deployment, while system testing tests integrated components to ensure they work together correctly.', 'Release testing is comprehensive and tests the complete system end-to-end, including all integrated components. It verifies that the system meets all stated requirements (functional and non-functional), handles expected workloads without degradation, and performs adequately. System testing occurs before release and tests scenarios that occur in the production environment. Release testing is often performed by dedicated test teams separate from development, providing objective assessment. Test scenarios include normal usage, boundary conditions, error handling, and performance under load.', 'Before releasing an e-commerce system, release testing verifies that users can register, browse products, add items to the cart, process payments, and receive confirmation emails. Performance testing verifies the system handles expected peak shopping day traffic without slowing down significantly.', 'Thorough release testing ensures that the complete system meets requirements and performs adequately before deployment to production.');
INSERT INTO questions_answers 
(unit_id, unit_name, question_keyword, question_title, definition, explanation, example, conclusion)
VALUES 
(5, 'Software Testing & Dependability', 'user testing acceptance testing', 'What is user testing and acceptance testing?', 
'User testing and acceptance testing verify that a system meets user expectations and business requirements, often involving actual users or representatives.', 'Acceptance testing is conducted by users or business representatives to verify that the system meets their requirements and can be accepted for operational use. User testing involves actual end users exercising the system in realistic scenarios. This testing reveals usability issues, missing features, and unmet expectations that technical testing might miss. User feedback is crucial for assessing whether the system truly solves their problems. User testing can occur in labs (controlled environment) or in the field (user\'s actual environment). Beta testing releases a pre-release version to real users for feedback.', 'Before deploying a hospital patient management system, hospital staff test it with real patient data and workflows. They provide feedback on usability, workflow alignment, and missing features. This user testing ensures the system integrates smoothly into their operations.', 'User and acceptance testing ensure that the final system meets real-world user needs and business objectives, preventing costly post-deployment failures.');
INSERT INTO questions_answers 
(unit_id, unit_name, question_keyword, question_title, definition, explanation, example, conclusion)
VALUES 
(5, 'Software Testing & Dependability', 'dependability reliability availability', 'What are dependability, reliability, and availability?', 
'Dependability is the ability of a system to perform reliably without failure, reliability is the probability of failure-free operation, and availability is the probability that a system is operational when needed.', 'Dependability encompasses reliability (how often failures occur), availability (proportion of time the system is working), and safety (no harm results from failures). Mean Time Between Failures (MTBF) measures reliability, while uptime percentage measures availability. A system might be highly reliable but with long recovery times, resulting in low availability; conversely, a system with frequent failures but quick recovery might maintain acceptable availability. Dependable systems require careful design, high-quality implementation, thorough testing, and operational practices that detect and respond to failures. Critical systems like aviation or medical devices require extremely high dependability.', 'An airline reservation system must be highly available (99.99% uptime expected during business hours) and reliable (data must be correct after thousands of transactions daily). This requires redundant hardware, backup systems, and rigorous testing.', 'Understanding dependability, reliability, and availability helps teams set appropriate quality targets and design systems accordingly.');
INSERT INTO questions_answers 
(unit_id, unit_name, question_keyword, question_title, definition, explanation, example, conclusion)
VALUES 
(5, 'Software Testing & Dependability', 'safety security critical systems', 'What are safety and security in critical systems?', 
'Safety refers to the absence of unintended harm, while security refers to protection against malicious attacks; both are critical considerations in systems with high-impact failures.', 'Safety-critical systems like medical devices, aircraft, and nuclear plants must be designed so failures don\'t cause harm. Techniques include redundancy (multiple independent systems), fail-safe design (failures default to safe states), and rigorous testing. Security-critical systems like banking and government systems must resist deliberate attacks. Techniques include encryption, authentication, access control, and intrusion detection. Some systems face both safety and security challenges; for example, medical device hacking is both a security and safety issue. Building dependable systems requires understanding threats and hazards specific to the domain.', 'A medical infusion pump must be designed so a software failure doesn\'t cause overdose (safety-critical). It must also prevent unauthorized wireless connection and drug tampering (security-critical). The system uses redundant sensors, fail-safe defaults, encryption, and authentication.', 'Safety and security are critical concerns in systems with high-impact consequences, requiring domain-specific design approaches and rigorous verification.');
INSERT INTO questions_answers 
(unit_id, unit_name, question_keyword, question_title, definition, explanation, example, conclusion)
VALUES 
(5, 'Software Testing & Dependability', 'fault tolerance redundancy', 'What is fault tolerance and how is it achieved through redundancy?', 
'Fault tolerance is the ability of a system to continue functioning correctly even when components fail, often achieved through redundancy.', 'Redundancy involves having multiple copies of critical components so if one fails, others can continue operation. Types include hardware redundancy (multiple processors), software redundancy (diverse implementations), and data redundancy (replicated data). When a failure is detected, the system must failover to the redundant component. Recovery procedures restore failed components to service. Redundancy increases cost and complexity but is essential for high-availability systems. N-modular redundancy uses N identical copies and consensus voting to mask failures. Active redundancy (all components working) provides better performance than standby redundancy (backup activated on failure).', 'A data center with redundant databases replicates data to multiple servers. If one server fails, others continue serving requests. Failed servers are identified and repaired while the system maintains availability. This redundancy costs more but ensures the system remains available despite hardware failures.', 'Redundancy is a proven approach to achieving fault tolerance, enabling systems to maintain service despite component failures.');
INSERT INTO questions_answers 
(unit_id, unit_name, question_keyword, question_title, definition, explanation, example, conclusion)
VALUES 
(5, 'Software Testing & Dependability', 'software reliability model', 'What are software reliability models?', 
'Software reliability models are mathematical models that predict failure rates and reliability based on testing data and historical information.', 'Software reliability models help predict how many bugs remain in software based on how many are found during testing. The basic assumption is that finding bugs and fixing them improves reliability. Models like exponential growth models assume bugs are found at a constant rate and fixing them proportionally improves reliability. Other models account for the decreasing rate of finding remaining bugs as development progresses (fewer bugs remain, finding them becomes harder). Reliability models help answer questions like \'Is the software reliable enough to release?\' or \'How much more testing is needed?\' However, models require sufficient test data to be accurate and don\'t account for certain failure types.', 'A reliability model predicts that after finding and fixing 90% of bugs, the remaining 10% will take disproportionately longer to find. This helps plan testing resources and set realistic reliability targets.', 'Software reliability models provide quantitative support for release decisions and testing planning, though must be used carefully with awareness of their limitations.');
INSERT INTO questions_answers 
(unit_id, unit_name, question_keyword, question_title, definition, explanation, example, conclusion)
VALUES 
(5, 'Software Testing & Dependability', 'testing strategies approaches', 'What are different testing strategies and approaches?', 
'Testing strategies are comprehensive plans for how testing is organized and conducted throughout the development process.', 'Testing can follow different strategies: top-down testing starts with system interfaces and gradually tests deeper components, useful when dependent stubs are expensive; bottom-up testing starts with individual components, useful when component testing is expensive; big-bang testing tests all components together (risky), or incremental testing integrates and tests gradually. Strategies can be functional (based on specified functions) or structural (based on code structure). Defensive programming assumes bugs exist and designs to minimize their impact. Destructive testing deliberately tries to break systems. Monkey testing uses random inputs to find unexpected failures. Effective projects combine multiple strategies based on project context and risks.', 'A web application might use bottom-up testing to thoroughly test backend services, functional testing to verify each feature requirement, and penetration testing to identify security vulnerabilities. Different strategies address different quality concerns.', 'Selecting appropriate testing strategies based on project context ensures efficient use of testing resources and comprehensive quality assurance.');

-- =====================================================
-- VERIFICATION QUERIES
-- =====================================================
-- Check total count
SELECT 'Total Questions' as label, COUNT(*) as count FROM questions_answers;

-- Check count per unit
SELECT unit_id, unit_name, COUNT(*) as count 
FROM questions_answers 
GROUP BY unit_id, unit_name 
ORDER BY unit_id;

-- =====================================================
-- SAMPLE RETRIEVAL QUERY
-- =====================================================
-- Example: Retrieve answer for a question
-- SELECT * FROM questions_answers WHERE question_keyword LIKE '%software%' LIMIT 1;

-- =====================================================
-- END OF DATABASE SETUP
-- =====================================================
